# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Teko-Dev-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'RxAlamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'AlamofireImage', '~> 3.5'
  pod 'FSPagerView'

end
